import {
	faCloud,
	faCloudBolt,
	faCloudMeatball,
	faCloudRain,
	faCloudShowersHeavy,
	faCloudSun,
	faCloudSunRain,
	faSmog,
	faSnowflake,
	faSun,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

export const weatherCode = {
	0: "Cer senin",
	1: "Senin",
	2: "Parțial înnorat",
	3: "Înnorat",
	45: "Ceață",
	48: "Ceață deasă",
	51: "Burniță ușoară",
	53: "Burniță moderată",
	55: "Burniță intensă",
	56: "Burniță înghețată ușoară",
	57: "Burniță înghețată intensă",
	61: "Ploaie ușoară",
	63: "Ploaie moderată",
	65: "Ploaie puternică",
	66: "Lapoviță ușoară",
	67: "Lapoviță intensă",
	71: "Ninsoare ușoară",
	73: "Ninsoare moderată",
	75: "Ninsoare puternică",
	77: "Ninsoare cu grindină",
	80: "Averse ușoare",
	81: "Averse moderate",
	82: "Averse puternice",
	85: "Averse de zăpadă ușoare",
	86: "Averse de zăpadă puternice",
	95: "Furtună",
	96: "Furtună cu grindină ușoară",
	99: "Furtună cu grindină puternică",
};
